### ISSUE TITLE
[question] chat transcripts email

### ISSUE THREAD

**Issue by ralph-e-boy** [zendesk/zendesk_sdk_chat_ios#33] opened 2015-11-11 20:11 UTC
Hi there

The chat transcript sent at the end of a chat session comes from noreply@zopim.com. Is there a way to disable this? 

thanks in advance,
--Ralph

**Comment by tecknut** [comment] 2015-11-12 15:06
Hi @ralph-e-boy, 

There is currently no supported way to do this. It's possible to achieve it using method swizzling, but that is something we wouldn't support if there were any issues caused by swizzling. 

Thanks

**Comment by ralph-e-boy** [comment] 2015-11-12 19:20
@tecknut  thanks for the info -- any plans to include this as configuration option?

**Comment by tecknut** [comment] 2015-11-12 19:23
@ralph-e-boy There are plans to include this yes, but I can't say when this will happen.

**Comment by schlan** [comment] 2015-12-10 13:46
Closing - duplicate of https://github.com/zendesk/zendesk_sdk_chat_ios/issues/27

**Closed by schlan** 2015-12-10 13:46 UTC
Labels: duplicate, enhancement
