### ISSUE TITLE
Follow of up Issue with scroll view starting under navigation bar in iOS < 11

### ISSUE THREAD

**Issue by Genhain** [zendesk/zendesk_sdk_chat_ios#178] opened 2017-11-22 03:00 UTC
In reference to #175 since i don't have the privileges to reopen the topic so this is a follow up

Here Are some screens of what i was talking about iOS 11 seems fine, anything else...not so much. on the first screen the first field for the name is behind the nav bar and in the chat itself my first message of hello is again under the nav bar.

[here is how i initialise it](https://gist.github.com/Genhain/0a24345237820535c585a1da3849ed31)

![When first starting a chat](https://user-images.githubusercontent.com/2082208/33054372-cc808710-ceb3-11e7-8dda-e105e57b8bb5.png)

<img width="477" alt="screen shot 2017-11-21 at 12 01 27 pm" src="https://user-images.githubusercontent.com/2082208/33054392-dee5012e-ceb3-11e7-8c34-03df719df2bb.png">

<img width="456" alt="screen shot 2017-11-22 at 10 57 05 am" src="https://user-images.githubusercontent.com/2082208/33107890-4b9a1302-cf74-11e7-8f93-3168d88b0226.png">
<img width="455" alt="screen shot 2017-11-22 at 10 57 56 am" src="https://user-images.githubusercontent.com/2082208/33107892-4df10c3c-cf74-11e7-913a-928107ead640.png">

**Comment by divo** [comment] 2017-11-27 15:55
@Genhain I am able to reproduce this issue. You are correct, it was introduced in response to [#175](https://github.com/zendesk/zendesk_sdk_chat_ios/issues/175).

This is because of [topLayoutGuide](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621367-toplayoutguide). 

> If a container navigation controller's navigation bar is visible and opaque, the navigation controller lays out the frontmost view controller's view so its top edge abuts the bottom of the navigation bar. In this case, the value of this property is 0.

If the bar is translucent the view is laid out underneath it. We no longer account for this.

Can you try disabling translucency on your nav controller and see that fixes it?

We will update you with an ETA on a proper fix when we know.

**Comment by Genhain** [comment] 2017-11-28 03:55
@divo Much appreciated, thank you

**Comment by baz8080** [comment] 2017-11-28 15:35
Hi @Genhain!
We have added the workaround to our [release notes](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/knownissues#v1.3.7.1) also. We are targeting a proper release to fix this in early 2018. We're currently working on the next version of the Support SDK.

**Comment by chaseacton** [comment] 2018-04-16 19:37
Any update for this? The recommended fix for disabling translucency on the navigation bar is not working on iOS 10.1 and with the latest chat SDK pod. I've attached a sample project demonstrating the bug.
[Zendesk Chat Test.zip](https://github.com/zendesk/zendesk_sdk_chat_ios/files/1916943/Zendesk.Chat.Test.zip)

**Comment by baz8080** [comment] 2018-04-27 14:35
@chaseacton We are going to look at a fix in our next sprint, which is in the next two weeks. We'll keep you updated.

**Comment by chaseacton** [comment] 2018-04-27 15:12
Thanks!

**Comment by parth51** [comment] 2018-05-14 08:57
Any update on this ?

**Comment by brendan-fahy** [comment] 2018-05-15 10:08
Hi @parth51, the gods of sprint planning have frowned upon us and the update right now is effectively the same as Barry's one above: it's in our current sprint to be fixed and we'll be looking to release the patch as soon as we've done our testing.

**Comment by baz8080** [comment] 2018-06-20 11:04
@parth51 the fix has been merged to our internal development repository, and we will be aiming to release it as soon as we can.

**Comment by divo** [comment] 2018-08-16 14:06
We released 1.4 today. It should fix this issue.

**Closed by divo** 2018-08-16 14:06 UTC
Labels: bug
