### ISSUE TITLE
End Chat showing a white blank view on iPad

### ISSUE THREAD

**Issue by SyedIsmailAhamed** [zendesk/zendesk_sdk_chat_ios#116] opened 2016-10-06 06:16 UTC
- SDK version:1.3.1.1
- Xcode version: 7or 8
- iOS or Simulator:iOS
- iOS Version:9.3
- Swift version:

Steps to Reproduce:
1. Start chat on iPad
   2.once the session is started tap on end chat
   ![img_0979](https://cloud.githubusercontent.com/assets/2704834/19142362/f35abb66-8bad-11e6-8e8a-6230330852cc.PNG)
   ![img_0980](https://cloud.githubusercontent.com/assets/2704834/19142361/f359cdd2-8bad-11e6-80f7-302c52d986cd.PNG)

**Comment by baz8080** [comment] 2016-10-06 09:47
@SyedIsmailAhamed Could you elaborate a little please? To me it looks like you started a chat modally from your own screen. If you end the chat, it dismisses the modal so you will be left back at your own screen.

**Comment by SyedIsmailAhamed** [comment] 2016-10-06 11:05
@baz8080 This happens only on iPad i do the same thing on iPhone it works, here is the code snippet, yes its true that i have my own screen and presenting the the chat from it, but i wonder why is it behaving differently on iPad.
    [ZDCChat startChatIn:self.navigationController withConfig:^(ZDCConfig *config) {
        if ([BFLDefaults isEmpty:userIdentificationToken]) {
            [ZDCChat instance].api.visitorInfo.name=@"";
            [ZDCChat instance].api.visitorInfo.email=@"";
            [ZDCChat instance].api.visitorInfo.phone=@"";
            config.preChatDataRequirements.name = ZDCPreChatDataOptionalEditable;
            config.preChatDataRequirements.email = ZDCPreChatDataOptionalEditable;
            config.preChatDataRequirements.phone = ZDCPreChatDataOptionalEditable;
        }
        else{
            [ZDCChat instance].api.visitorInfo.name=userName;
            [ZDCChat instance].api.visitorInfo.email=emailAddress;
            [ZDCChat instance].api.visitorInfo.phone=phoneNumber;
        }
        config.preChatDataRequirements.message = ZDCPreChatDataOptionalEditable;
    }];

**Comment by SyedIsmailAhamed** [comment] 2016-10-06 11:20
Am not sure why the issue is happening on iPad but I have found a workaround for this, here is the code snippet,

-(void)viewDidLoad
{
    if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad)
    {
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(dismissingChatController) name:@"DismissingChatControllerNotification" object:nil];
    }
    else{
        [self configureChat];
    }
}
-(void)viewWillAppear:(BOOL)animated{
    if (UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPad)
    {
    [self configureChat];
    }
}

-(void)configureChat
{
       [ZDCChat startChatIn:self.navigationController withConfig:^(ZDCConfig *config) {
        
        if ([BFLDefaults isEmpty:userIdentificationToken]) {
            [ZDCChat instance].api.visitorInfo.name=@"";
            [ZDCChat instance].api.visitorInfo.email=@"";
            [ZDCChat instance].api.visitorInfo.phone=@"";
            
            config.preChatDataRequirements.name = ZDCPreChatDataOptionalEditable;
            config.preChatDataRequirements.email = ZDCPreChatDataOptionalEditable;
            config.preChatDataRequirements.phone = ZDCPreChatDataOptionalEditable;
        }
        else{
            [ZDCChat instance].api.visitorInfo.name=userName;
            [ZDCChat instance].api.visitorInfo.email=emailAddress;
            [ZDCChat instance].api.visitorInfo.phone=phoneNumber;
        }
               config.preChatDataRequirements.message = ZDCPreChatDataOptionalEditable;
    }];
}
-(void)dismissingChatController
{
    NSLog(@"dismissing chat controller called");
    [self dismissViewControllerAnimated:YES completion:nil];
}


//The Notification is being posted from chat styling class
+ (void) chatUnloaded:(NSNotification*)notification
{
    // The Chat UI has been dismissed
    [[NSNotificationCenter defaultCenter] postNotificationName:@"DismissingChatControllerNotification" object:self];
}

Yes, you read it right, configuring the chat in viewdidload for iPhone and viewwillapear for iPad and having a custom notification posted from chatunloaded of chatstyling class resolved this.

**Comment by oarrabi** [comment] 2016-10-11 18:56
Hello @SyedIsmailAhamed ,

I have used the code you posted and tried to reproduce the issue, please see the gif bellow:

![oct-11-2016 19-52-58](https://cloud.githubusercontent.com/assets/1461052/19284144/9b7fe2fc-8fec-11e6-9699-9e9ebd5014e3.gif)

Since I am unable to reproduce the bug, would it be possible to share a small project that reproduces the issue?

Thanks

**Comment by oarrabi** [comment] 2016-12-06 10:49
Hello @SyedIsmailAhamed, 

I am going to close this issue for now, if this issue persists, or if you have any other question. Please dont hesitate to contact us :)

**Closed by oarrabi** 2016-12-06 10:49 UTC
Labels: pending information
