### ISSUE TITLE
Crash on [ZDCChatView tableView:cellForRowAtIndexPath:]

### ISSUE THREAD

**Issue by eikebartels** [zendesk/zendesk_sdk_chat_ios#78] opened 2016-04-20 15:54 UTC
I discovered a crash in crittercism. See stack trace below 

> unable to dequeue a cell with identifier (null) - must register a nib or a class for the identifier or connect a prototype cell in a storyboard

```
CoreFoundation 0x21e61b8b __exceptionPreprocess + 124
1	libobjc.A.dylib 0x2161edff objc_exception_throw + 36
2	CoreFoundation 0x21e61a61 +[NSException raise:format:arguments:] + 102
3	Foundation 0x2264872b -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 88
4	UIKit 0x265b8f1d -[UITableView dequeueReusableCellWithIdentifier:forIndexPath:] + 234
!	5	Volo 0x0084ab39 -[ZDCChatView tableView:cellForRowAtIndexPath:] (ZDCChatView.m:308)
6	UIKit 0x2677bc51 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 670
7	UIKit 0x2677bd91 -[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 66
8	UIKit 0x2676b26d -[UITableView _updateVisibleCellsNow:isRecursive:] + 2266
9	UIKit 0x2656813b -[UITableView cellForRowAtIndexPath:] + 148
10	Volo 0x0084b8cb -[ZDCChatView agentEvent:] (ZDCChatView.m:532)
11	CoreFoundation 0x21e13345 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 10
12	CoreFoundation 0x21e12d53 _CFXRegistrationPost + 396
13	CoreFoundation 0x21e12b29 ___CFXNotificationPost_block_invoke + 38
14	CoreFoundation 0x21e69f63 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1332
15	CoreFoundation 0x21d720eb _CFXNotificationPost + 484
16	Foundation 0x225b7b17 -[NSNotificationCenter postNotificationName:object:userInfo:] + 68
17	Volo 0x00822b75 __54-[ZDCChatDataNode sendNotificationsForPath:forUpdate:]_block_invoke (ZDCChatDataNode.m:380)
18	libdispatch.dylib 0x219f3cbf _dispatch_call_block_and_release + 8
19	libdispatch.dylib 0x219f3cab _dispatch_client_callout + 20
20	libdispatch.dylib 0x219f8559 _dispatch_main_queue_callback_4CF + 1530
21	CoreFoundation 0x21e237d5 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 6
22	CoreFoundation 0x21e21ccf __CFRunLoopRun + 1588
23	CoreFoundation 0x21d70289 CFRunLoopRunSpecific + 514
24	CoreFoundation 0x21d7007d CFRunLoopRunInMode + 106
25	GraphicsServices 0x2338caf9 GSEventRunModal + 158
26	UIKit 0x2649b2c5 UIApplicationMain + 142
27	Volo 0x00191223 main (main.m:16)
28	libdyld.dylib 0x21a1c873 start + 0
```

**Comment by Lbenoit** [comment] 2016-04-25 20:17
I'm also seeing this crash frequently since updating to version 1.2.0.1

**Comment by elaser** [comment] 2016-04-25 20:22
Looks like the same issue as #39 .  Definitely still not resolved.

**Comment by oarrabi** [comment] 2016-04-26 15:16
Hello,

Unfortunately, I am unable to reproduce this issue.

Do you have any steps that reproduces this issue? 
Can you also provide the version of the iOS and the device that this crash happens on?

Thanks,

**Comment by eikebartels** [comment] 2016-04-29 15:51
Hey, 

this ticket should mark as bug because it is defiently one. 

@oarrabi The crash happens for example iPhone 6 / 9.3

I think the Crash message is quite clear 

> unable to dequeue a cell with identifier (null) - must register a nib or a class for the identifier or connect a prototype cell in a storyboard

Your are trying to access a cell with identifier (null) in 
`-[ZDCChatView tableView:cellForRowAtIndexPath:]`

**Comment by stephenkopylov** [comment] 2016-05-07 09:02
Same thing here. A lot of users faced it =(

![screen shot 2016-05-07 at 11 59 33](https://cloud.githubusercontent.com/assets/5202281/15091228/346f7f40-144b-11e6-825e-ebfef6ea1ec6.png)
![screen shot 2016-05-07 at 12 00 46](https://cloud.githubusercontent.com/assets/5202281/15091234/5c814432-144b-11e6-8821-87f222c3d403.png)

**Comment by eikebartels** [comment] 2016-05-13 10:43
Any news on this?

**Comment by elaser** [comment] 2016-05-13 14:56
agree with @eikebartels . any updates?

**Comment by stephenkopylov** [comment] 2016-05-13 14:59
yep, about month to fix this issue =(

**Comment by brendan-fahy** [comment] 2016-05-16 10:10
Hi guys,

This has been a difficult problem to pin down, and much of our efforts over the last month have been in trying to recreate the problem. In doing this, we found a handful of edge cases that can cause this crash to happen.
The fix for this is a fairly substantial code rewrite to accommodate these edge cases.
Our immediate focus is on trying to find a workaround to reduce the impact of this issue whilst we work on that major change.
Please continue to follow updates to this issue, and we'll come back with more info on both of these actions as soon as we have it.
Thanks.

**Comment by TofPlay** [comment] 2016-05-26 07:00
## Same issu here 
Return by Crashlytics:
![image](https://cloud.githubusercontent.com/assets/1082222/15566215/e1f42c46-231f-11e6-957a-9220737cd2c5.png)
![image](https://cloud.githubusercontent.com/assets/1082222/15566241/fd8b317a-231f-11e6-88f7-0472310a3f6f.png)
![image](https://cloud.githubusercontent.com/assets/1082222/15566265/25cb5bf6-2320-11e6-9832-e59665965b71.png)

**Comment by oarrabi** [comment] 2016-05-30 09:41
Hello @TofPlay,

We are narrowing down on this issue, however, we are still unable to reproduce it. Thanks for the additional info. I will update you when we do more progress on it.

**Comment by TofPlay** [comment] 2016-05-30 12:09
@oarrabi your welcome. I hope it's will help and you will able to fix it soon. In the midtime my app continues to crash regularly because of your component :(

**Comment by mathewcropper** [comment] 2016-05-31 13:29
Hi folks. A fresh update on this issue.

As mentioned earlier, there's a rewrite that needs to happen to make this work. To make sure we get it right, we are following the same approach as with the Support SDK. We are currently splitting the Chat SDK into two parts; UI, and providers.

This enables us to do two things. Firstly, when that is released, you're free to take the providers and build your own UI (a common feature request). Secondly, it sets us up with a much better foundation for fixing the state issues that cause this crash.

I'd like to echo what others on the team have said, and apologise for this issue. I appreciate it is frustrating and has an impact on your end-users. We'll keep the updates coming as and when we have something substantial to share.

**Comment by eikebartels** [comment] 2016-05-31 13:37
Hey @mathewcropper, thanks for the update. Do you have a estimated time frame for this. So that we can communicate this to your heads?

**Comment by mathewcropper** [comment] 2016-05-31 13:43
Hi @eikebartels. I can confirm that this is being actively worked on at the moment. We're progressing as fast as we can, with the end goal of fixing this issue, but I can't confirm a timeline right now. 

I want to see the back of this bug as much as you, but it is a chunky piece of work if we want to get it right. 

If you'd like to escalate this to your account manager, feel free to point them in my direction. In the meantime, I'll continue to update here as and when I have something to share.

Thank you again for your continued patience.

**Comment by TofPlay** [comment] 2016-05-31 14:13
Hi @eikebartels thank you for the update and your efforts to resolve this issue as soon as possible.

Here my update:
Number of crashs the last 6 days
![image](https://cloud.githubusercontent.com/assets/1082222/15677387/6465fd84-274a-11e6-913c-82a36020208e.png)

**Comment by TofPlay** [comment] 2016-06-07 12:15
@mathewcropper any news?

**Comment by mathewcropper** [comment] 2016-06-07 12:24
Hi @TofPlay! The work on splitting the UI and API providers is coming along well. I've also just finished planning the work that follows, and the fix for these issues is at the very top of the priority list for the team.

In terms of timelines, I'm expecting the UI/provider split to come in around the end of the month, and then we'll be rewriting the parts of the UI that are causing the problem. The work for that isn't estimated yet, so I can't give a reliable timeline for that side of things just yet.

Apologies to all on the thread for the length of time this is taking to resolve. I know this isn't ideal for any of you. This was an unpleasant piece of technical debt and we're racing to resolve it as fast as we can, and we're making good progress.

Hope that update helps. Thanks for chasing me to provide it 😄

**Comment by jontelang** [comment] 2016-06-08 05:25
Just noting that we are also facing crashes like this.

**Comment by brunobar79** [comment] 2016-06-13 16:04
Hey guys, I understand that in order to fix this properly, you need to rewrite a bunch of stuff but based on the times that you are talking about in the previous comments,  it looks like it's gonna take some time.  This was reported on April 20, and you're gonna start rewriting part of the UI next month and there's still no potential release date.

Have you considered a short term fix, that might not fix it 100%?  If it makes it any better, that will work for all of us...

**Comment by mathewcropper** [comment] 2016-06-20 10:47
Hi folks. A Monday morning update for you.

The UI/API split is now in code review, which will be followed by QA. This is on track with our plan to try to get this out towards the end of the month.

Now that this is done, we're starting the work on the crash fix itself. The working assumption is that code review and QA will not highlight any serious changes to the work done to date.

Thanks, as always, for your patience on this.

**Comment by mathewcropper** [comment] 2016-06-21 04:58
I'm looking into the possibility of sharing pre-release alpha builds of the Chat SDK for iOS whilst we work on this issue. As one of the crashes of this type has been very difficult to reproduce, it would be helpful for us to get some real world validation of our work in progress.

Would anybody on this thread be open to collaborating in this way?

**Comment by mathewcropper** [comment] 2016-06-27 09:18
The work on this is going extremely well. We're aiming to include updates in the next version of the Chat SDK that deal with this (and similar) crashes, so you will have both the UI/API split _and_ stability improvements.

The code is going through review and QA at the moment, and undoubtedly there will be some tweaks. When I have a firmer timeline for release, I'll update this thread again.

**Comment by TofPlay** [comment] 2016-06-30 08:44
Thanks for the update
I look forward to this new version 😊

**Comment by mathewcropper** [comment] 2016-07-18 13:00
I'm pleased to announce that v1.3.0.1 of the Chat SDK for iOS is now live, containing fixes for this issue. The release notes for this update are [here](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/releasenotes), along with migration guidance [here](https://developer.zendesk.com/embeddables/docs/ios-chat-sdk/migration).

I'll close this issue, but will continue to monitor for your feedback. If you find the crash occurring again when you are running on this version, please let us know.

I know that this has been quite a wait for you, and I'd like to thank you for your patience, as well as for being so incredibly cooperative in helping us get to the bottom of this.

**Closed by mathewcropper** 2016-07-18 13:00 UTC
Labels: bug, fixed: 1.3.0.1

**Comment by TofPlay** [comment] 2016-07-21 06:46
Hi @mathewcropper I have an issu with this version  (ticket #105)

**Comment by TofPlay** [comment] 2016-07-21 13:49
Hi @mathewcropper take also a look to the ticket #104
