### ISSUE TITLE
Overwriting saved name and email values on offline message form doesn't work

### ISSUE THREAD

**Issue by dangochi** [zendesk/zendesk_sdk_chat_ios#118] opened 2016-10-11 19:59 UTC
- SDK version: 1.3.2.1
- Xcode version: 8 (8A218a)
- iOS or Simulator: both
- iOS Version: 10.0.2

Steps to Reproduce:
1. open chat when no agents online, fill out email and name, send offline message
2. open new chat when no agents online, change saved name/email, send offline message
3. notice name/email in new offline message are using pre-filled form data instead of what the user updated with

If I could capture the updated information that the user put into that form, I could probably just call `[ZDCChat updateVisitor:]` with the new details, but I haven't seen a way to do that.

**Comment by RonanMcH** [comment] 2016-10-14 10:42
Hi @dangochi ,
Thanks for pointing this out. I can confirm it is a bug in the SDK. I have created an internal ticket to track the issue.
Thanks,
Ronan.

**Comment by baz8080** [comment] 2019-02-19 16:00
closing the issue because of its age. We're actively working on Chat SDK V2. We have this issue tracked internally. It's more a session management and timing issue rather than a bug. Rest assured, it won't be there in V2

**Closed by baz8080** 2019-02-19 16:00 UTC
Labels: bug
