### ISSUE TITLE
Text input bar is twice expected height

### ISSUE THREAD

**Issue by brucedaniel** [zendesk/zendesk_sdk_chat_ios#14] opened 2015-10-01 15:46 UTC
![simulator screen shot oct 1 2015 8 44 16 am](https://cloud.githubusercontent.com/assets/1004542/10225704/d85280f6-6818-11e5-888a-e8dfeeec21d4.png)

**Comment by grahamcruse** [comment] 2015-10-07 02:47
Hi,

Can you provide some replication steps for producing this?

Thanks

Graham

**Comment by grahamcruse** [comment] 2015-10-12 05:12
@brucedaniel we have located the issue here and the fix will be in the next patch.

**Comment by tecknut** [comment] 2015-11-25 13:44
@brucedaniel This issue has been open a while now. Has this issue been solved for you?

**Comment by emjoseph** [comment] 2015-12-07 23:35
I'm having the same issue on iPhone 6 - iOS 9.1

**Comment by oarrabi** [comment] 2015-12-11 19:50
@emjoseph Can you please make sure you are using the latest version `1.1.2` and let us know if its still an issue for you?

**Comment by oarrabi** [comment] 2015-12-23 09:34
I will be closing this issue since there was no reply in a while. Please feel free to reopen if the issue is still there.

**Closed by oarrabi** 2015-12-23 09:34 UTC
Labels: bug

**Comment by JacobJT** [comment] 2018-06-15 20:45
I'm experiencing this issue. I was on 1.3.2.1 and just updated to 1.3.7.1, the issue is in both. 

When I first open the chat, regardless if it's a new one, old one, modal, or pushed to a nav controller, the input bar is twice the expected height.

Additionally, if I press "Done", it goes back to what looks like normal, although the status bar is miscolored, not matching the navigation bar's color.  Then, if I tap the input bar again, the keyboard opens, and the input bar is all the way at the top, with a huge space between it and the keyboard.

![image from ios](https://user-images.githubusercontent.com/5605965/41488750-7993e1fa-70bb-11e8-9507-0ed6d80265d4.png)
![image from ios 1](https://user-images.githubusercontent.com/5605965/41488753-7b54e75a-70bb-11e8-8113-0e5b37381bc4.png)
![image from ios 2](https://user-images.githubusercontent.com/5605965/41488755-7d73d910-70bb-11e8-85f0-ee1a531cc5b4.png)
