### ISSUE TITLE
End Chat not working like expected

### ISSUE THREAD

**Issue by eikebartels** [zendesk/zendesk_sdk_chat_ios#67] opened 2016-03-09 17:01 UTC
The provided function to end the chat is not working like expected 
`[ZDCChat endChat];`

Our flow:

- User opens chatUI and start chatting 
- User close the chatUI (not ended)
- 1 minute past (1 minute just for test purpose) 
- We trigger `[ZDCChat endChat];` to force a new chat session 
- User opens chat. **Old session still alive**

**Comment by ndobri** [comment] 2016-03-10 16:50
Hi eikebartels, 

In our test we don't see any issues with `[ZDCChat endChat];` not ending the chat session. Could it be that your app does not stay in the background for long enough to execute that function. Maybe we're not testing the same use case, so can I ask that you provide more details of the reproduction steps?

Thanks.

**Comment by eikebartels** [comment] 2016-03-10 16:52
I trigger `[ZDCChat endChat];` manually like in the issue described. To test this, just call `[ZDCChat endChat];` with the ChatUI hidden after a couple of seconds

**Comment by oarrabi** [comment] 2016-03-11 15:47
Hello @eikebartels,

We are not able to reproduce this issue at the moment,
Would you be able to provide us with a code snippet showing the code you are using to end the chat?
It would be even better if you share a project or a project segment that shows your particular use case.

Thanks.

**Comment by oarrabi** [comment] 2016-04-14 10:32
I will close this issue now, if it stills persist, please don't hesitate to reopen it.

**Closed by oarrabi** 2016-04-14 10:32 UTC
Labels: pending information
