### ISSUE TITLE
[ZDCChatView scrollToLast:] Crash

### ISSUE THREAD

**Issue by ajumalebrahim** [zendesk/zendesk_sdk_chat_ios#152] opened 2017-06-28 08:09 UTC
##- SDK version: 1.3.2.1
- Xcode version: 8.3.3
- iOS or Simulator: IOS
- iOS Version: 11 beta, 10, 9 ,8
- Swift version: 3 ( Our project was in Objective c, Now we use both Objective c and Swift 3.)

Steps to Reproduce:
I don' t the steps to reproduce but its happening for the Appstore build. This issue is already posted but its now closed and i commented on the same issue but i did not get any response so am creating this, [Here is the old post](https://github.com/zendesk/zendesk_sdk_chat_ios/issues/79)

Adding an image from crashlytics :
<img width="1588" alt="screen shot 2017-06-28 at 11 06 21 am" src="https://user-images.githubusercontent.com/2928956/27626784-0837b2e0-5bf2-11e7-90a6-fdf8ac6dc992.png">
I believe this image will help you where exactly crashing. 
 Please help and Thanks.

**Comment by tecknut** [comment] 2017-06-28 10:41
Hey @ajumalebrahim, 

We've been looking into this. From other example crashes we found online, when a `scrollToRowAtIndexPath:atScrollPosition:animated:` `NSRangeException` reports that row X is out of range for the bounds Y where X is the same value as Y, the root cause is a timing issue. In the report from the closed issue as well as the one above the row and bounds are the same. 

The general solution to this crash is to dispatch the call to scroll to last on the main queue with GCD. This however is not really a solution to the problem, perhaps only working for some instances where a crash would other wise happen.

How many crashes are you seeing per week?

Thanks, 
Alan

**Comment by ajumalebrahim** [comment] 2017-06-29 06:11
Hi Alan, 

  Thanks for your response, we are getting around 750 crashes per week.

**Comment by ajumalebrahim** [comment] 2017-07-12 13:21
Ok thank you!. Awaiting for the new version. 👍 .

**Comment by jstheoriginal** [comment] 2018-01-13 16:38
Hi Zendesk Team.

This is still very much an issue and does not leave a good impression for those looking for support when the app crashes.

Any updates on solutions?

**Comment by brendan-fahy** [comment] 2018-01-22 14:26
Hi @jstheoriginal, unfortunately there is no update at this time. The work mentioned above was delayed, and I can't give an ETA for the new version. Sorry to be the bearer of bad news.

**Comment by jstheoriginal** [comment] 2018-01-22 14:28
Thanks @brendan-fahy. Do you know the root cause that triggers this? Is it caused by pre-sending messages that would make the chat need to scroll because it doesn't fit in the main chat window?

**Comment by divo** [comment] 2018-01-26 09:42
@jstheoriginal how frequently are you seeing these crashes? We have never been able to pin them all down. We did solve a lot of them some time ago but a few remain. We want to gut the SDK and rebuild it but we simply haven't had the time. Any information you provide about frequency would be appreciated.

**Comment by stefandouganhyde** [comment] 2018-01-30 16:34
Hi @divo. I'm experiencing this crash too so I've been following this issue.

Your question about frequency prompted me to investigate a little deeper. If I look at these crashes as a proportion of chat sessions, I calculate that approximately 1.3% of users who participate in Zendesk chats will experience this crash, which seems very high to me.

Hopefully, this data helps you prioritise this fix accordingly.

**Comment by baz8080** [comment] 2018-01-31 11:23
Thanks for the data @stefandouganhyde
I passed it along to the people who need to know.

**Comment by Spr-Luis** [comment] 2018-02-08 17:15
iOS or Simulator: iOS
iOS Version: 10 & 11

Hi, I have the same problem in Urbvan application for iOS, every day we have more that 40 users with this problem, our service requires Zendesk Chat to bring our users the best experience. We need an fix. :(

**Comment by Spr-Luis** [comment] 2018-06-18 20:42
When you will update the SDK for fix this issue? Customer support are becoming crazy because they lost the connection with our clients. 👎 👎

**Comment by baz8080** [comment] 2018-06-20 15:44
We've attempted to fix this issue in the version that we'll be releasing in the near term. The lack of reproducibility hampered our efforts to do that. We'll post back here when the version is released. We hope it'll improve the issue.

**Comment by divo** [comment] 2018-08-16 14:04
We have released 1.4 today. As we were never able to replicate this I can't say we fixed it with certainty. We did try.

Can you give it go and let us know how it goes?

**Comment by Spr-Luis** [comment] 2018-08-16 20:50
https://cocoapods.org/pods/ZDCChat#changelog

**Comment by baz8080** [comment] 2019-02-19 11:41
I'm closing this as we've not been receiving new reports of the issue. In any case, we're actively working on V2 of the SDK, which will be based on a different codebase.

**Closed** 2019-02-19 11:40 UTC
Labels: bug

**Comment by Spr-Luis** [comment] 2019-02-19 23:32
For when do you plan to launch V2? My team is planning change to Intercom for issues with this version of Zendesk Chat

**Comment by baz8080** [comment] 2019-02-20 12:55
@Spr-Luis there are no ETAs, but we'll be getting an initial version out in Q2. I appreciate that might not fit your timelines, and that you might need to migrate to Intercom. Perhaps you'll try V2 when it comes out. Thanks!
