### ISSUE TITLE
"Reconnecting..." banner never disappears despite being reconnected  

### ISSUE THREAD

**Issue by amsalt18** [zendesk/zendesk_sdk_chat_ios#216] opened 2018-10-31 20:33 UTC
The "Reconnecting" banner won't disappear despite being reconnected with an agent. 

![reconnecting](https://user-images.githubusercontent.com/20688869/47816848-8dab9f80-dd2a-11e8-89cd-3f5b2e307966.png)

- SDK version: 1.4.0
- Xcode version: 10.1 (10B61)
- iOS or Simulator: iPhone XS Max
- iOS Version: 12.0.1
- Swift version: 4.2

Steps to Reproduce:

1. Start a chat
2. Leave the application 
3. Return after the timeout period has been completed

Expected: After you are reconnected with an agent, the "reconnecting..." banner disappears.
Result: The "reconnecting..." banner persists. 

cc @mlbaron

**Comment by Jiaguanglei0418** [comment] 2018-11-06 12:17
i also have this bug, who can give a help?

**Comment by HamstringAssassin** [comment] 2018-11-08 13:02
Hi @amsalt18 & @Jiaguanglei0418, 

Thanks for getting in touch. I'm having some trouble reproducing from the steps given. 
Just to clarify, is the device online or offline? or are you saying that it's somehow related to the agent being online? 

I've been testing by switching to airplane mode and the "reconnecting" banner is removed every time. 

Thanks, 
Al

**Comment by amsalt18** [comment] 2018-11-08 16:21
Hi @HamstringAssassin, thanks for the response! To answer your questions: 

The device was always online and connected to the internet. 

If I had to guess, I would say it has to do with the agent being disconnected to the chat after a timeout (when the customer doesn't respond, it automatically ends the chat after some time) and then when the customer comes back. 

What happens is: the customer re-opens the chat, it restarts the chat (but the user sees the same chat that they've always seen), they are connected with a new live chat agent, and the "Reconnecting..." banner stays there.

**Comment by Jiaguanglei0418** [comment] 2018-11-19 05:58
user dismiss the chatViewController before a connected chat established will make this reconnecting case when start a chat again.

**Comment by HamstringAssassin** [comment] 2018-11-26 15:19
Hi @amsalt18 & @Jiaguanglei0418, 

Unfortunately, I still can't repo the issue. Just to possibly rule out the issue being a difference in our configurations, Could you try reproduce the issue with the sample app in this repo and your own config? 

Thanks a mil,
Al

**Comment by RonanMcH** [comment] 2018-12-06 10:57
@amsalt18 and @Jiaguanglei0418 ,
have either of you had any luck reproducing the sample app. This would help us determine if it was a possible in your chat admin configuration or an issue in the SDK?

**Comment by amsalt18** [comment] 2018-12-06 15:44
Hi @RonanMcH & @HamstringAssassin, our iOS engineer working with this SDK has been out. Will get back to you once we have the capacity to test this.

**Comment by HamstringAssassin** [comment] 2019-02-12 11:37
Hi @amsalt18, 

As there hasn't been an update since December I'm going to close this ticket. If you get more info, or the issue persists, feel free to open a new issue and link to this one. 

Thanks a mil, 
Al

**Closed by HamstringAssassin** 2019-02-12 11:37 UTC
Labels: pending information
